#10.36.142.126 192.168.3.17
dubbo:
  application:
    name: student_provider
  registry:
    address: zookeeper://10.36.142.31:2181
  protocol:
    name: dubbo
    port: 20880
spring:
  datasource:
    url: jdbc:mysql:///dubbo_student
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qf.entity